// MIT License
//
// Copyright (c) 2026 Michael Ledour
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and /or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions :
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Integration tests: drive the real OpenXrLayer class (from layer.cpp) against
// the mock runtime defined in mock_runtime.{h,cpp}. These tests link the
// layer's dispatch machinery so they cover the actual virtual-method plumbing
// generated by dispatch_generator.py — not a hand-rolled copy.
//
// What we do NOT cover here (intentionally): the loader handshake
// (xrNegotiateLoaderApiLayerInterface, xrCreateApiLayerInstance). Those
// need a live loader and are verified by the end-to-end job on a self-hosted
// runner. Everything else that happens after the layer has been handed an
// XrInstance — config parsing, swapchain-size scaling, and FOV narrowing —
// is in scope.

#include "pch.h"

#include "mock_runtime.h"

#include <layer.h>
#include <utils/crop_math.h>

#include <doctest/doctest.h>

#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <random>
#include <thread>

using openxr_api_layer::GetInstance;
using openxr_api_layer::OpenXrApi;

namespace {

// Every TEST_CASE creates a fresh layer singleton + mock state, so tests are
// order-independent. We also isolate %LOCALAPPDATA% to a unique temp dir per
// test so settings.json handling is deterministic on CI where the real
// %LOCALAPPDATA%\XR_APILAYER_MLEDOUR_fov_crop\ might exist with user data.
struct LayerFixture {
    std::filesystem::path configDir;

    LayerFixture() {
        mock::reset();
        openxr_api_layer::ResetInstance();

        // Unique temp dir avoids clashes if tests run in parallel one day.
        std::random_device rd;
        auto suffix = std::to_string(rd());
        configDir = std::filesystem::temp_directory_path() /
                    ("openxr-layer-test-" + suffix);
        std::filesystem::create_directories(configDir);
        openxr_api_layer::localAppData = configDir;
        openxr_api_layer::dllHome = configDir;
    }

    ~LayerFixture() {
        openxr_api_layer::ResetInstance();
        std::error_code ec;
        std::filesystem::remove_all(configDir, ec);
    }

    // Writes the global settings.json template into the fixture's
    // localAppData. On the next boot(), the layer bootstraps the per-app
    // config (test_settings.json) from this file. Pass empty string to skip
    // (layer will use defaults or whatever a previous writePerAppSettings
    // put in place).
    void writeSettings(const std::string& json) {
        if (json.empty()) return;
        std::ofstream f(configDir / "settings.json");
        f << json;
    }

    // Writes directly to the per-app config file (test_settings.json) that
    // the fixture's boot() will use (applicationName = "test" -> slug
    // "test"). Use this for post-boot mutations that need the live-edit
    // watcher to observe the change — writeSettings() targets the template,
    // which the watcher does not monitor.
    void writePerAppSettings(const std::string& json) {
        if (json.empty()) return;
        std::ofstream f(configDir / "test_settings.json");
        f << json;
    }

    // Brings the layer up the same way xrCreateApiLayerInstance would:
    // wire GIPA -> call xrCreateInstance -> resolve every function we plan to
    // exercise (so the m_xrFoo pointers in OpenXrApi are populated via the
    // generated xrGetInstanceProcAddrInternal path).
    OpenXrApi* boot() {
        OpenXrApi* layer = GetInstance();
        REQUIRE(layer != nullptr);

        // XrInstance here is a fake handle — the layer never dereferences it,
        // just threads it back to the mock via m_xrGetInstanceProcAddr.
        XrInstance fakeInstance = reinterpret_cast<XrInstance>(static_cast<uintptr_t>(0xBEEF));
        layer->SetGetInstanceProcAddr(&mock::xrGetInstanceProcAddr, fakeInstance);

        XrInstanceCreateInfo ici{XR_TYPE_INSTANCE_CREATE_INFO};
        std::strncpy(ici.applicationInfo.applicationName, "test", XR_MAX_APPLICATION_NAME_SIZE - 1);
        ici.applicationInfo.apiVersion = XR_CURRENT_API_VERSION;

        REQUIRE(layer->xrCreateInstance(&ici) == XR_SUCCESS);

        // Resolve the entry points the tests will call. This is what the
        // loader does after xrCreateApiLayerInstance: each of these calls
        // populates m_xrFoo inside OpenXrApi via the generated
        // xrGetInstanceProcAddrInternal. We never use the returned function
        // pointers — we go through the virtual methods instead.
        //
        // We explicitly target OpenXrApi::xrGetInstanceProcAddr (the base,
        // non-bypassed implementation). The OpenXrLayer override short-circuits
        // to raw runtime pointers when m_bypassApiLayer is true, which skips
        // the m_xrFoo population and would leave the test calling null in
        // bypass-enabled test cases. Going through the base always populates
        // the dispatch table so subsequent virtual calls are safe to make;
        // the override's enabled-check still governs whether the layer
        // mutates results.
        auto resolve = [&](const char* name) {
            PFN_xrVoidFunction fn = nullptr;
            REQUIRE(layer->OpenXrApi::xrGetInstanceProcAddr(fakeInstance, name, &fn) == XR_SUCCESS);
        };
        resolve("xrGetSystem");
        resolve("xrCreateSession");
        resolve("xrEnumerateViewConfigurationViews");
        resolve("xrLocateViews");

        return layer;
    }
};

constexpr float kDefaultLeftAngle = -0.90f;
constexpr float kDefaultRightAngle = 0.90f;
constexpr float kDefaultUpAngle = 0.70f;
constexpr float kDefaultDownAngle = -0.70f;

XrFovf defaultFov() {
    return XrFovf{kDefaultLeftAngle, kDefaultRightAngle, kDefaultUpAngle, kDefaultDownAngle};
}

} // namespace

// ---------------------------------------------------------------------------
// xrEnumerateViewConfigurationViews: recommended dims shrink per config
// ---------------------------------------------------------------------------

TEST_CASE("integration: xrEnumerateViewConfigurationViews scales recommended dims") {
    LayerFixture fx;
    // 10/10/15/20% crop -> factors 0.9/0.9/0.85/0.80.
    // scaleSwapchainExtents uses min(left,right)=0.9 for width, min(top,bot)=0.80 for height.
    // 2000*0.9 = 1800 (8-aligned: 1800), 2200*0.8 = 1760 (8-aligned: 1760).
    fx.writeSettings(R"({
        "enabled": true,
        "crop_left_percent": 10,
        "crop_right_percent": 10,
        "crop_top_percent": 15,
        "crop_bottom_percent": 20
    })");
    mock::state().recommendedWidth = 2000;
    mock::state().recommendedHeight = 2200;
    mock::state().viewCount = 2;

    auto* layer = fx.boot();

    uint32_t count = 0;
    REQUIRE(layer->xrEnumerateViewConfigurationViews(
                reinterpret_cast<XrInstance>(static_cast<uintptr_t>(0xBEEF)),
                static_cast<XrSystemId>(1),
                XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO,
                0, &count, nullptr) == XR_SUCCESS);
    REQUIRE(count == 2);

    std::vector<XrViewConfigurationView> views(count, {XR_TYPE_VIEW_CONFIGURATION_VIEW});
    REQUIRE(layer->xrEnumerateViewConfigurationViews(
                reinterpret_cast<XrInstance>(static_cast<uintptr_t>(0xBEEF)),
                static_cast<XrSystemId>(1),
                XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO,
                count, &count, views.data()) == XR_SUCCESS);

    // Expected: 2000 * 0.9 = 1800, aligned-down to 8 -> 1800. 2200 * 0.8 = 1760.
    CHECK(views[0].recommendedImageRectWidth == 1800u);
    CHECK(views[0].recommendedImageRectHeight == 1760u);
    CHECK(views[1].recommendedImageRectWidth == 1800u);
    CHECK(views[1].recommendedImageRectHeight == 1760u);
}

TEST_CASE("integration: bypass (enabled=false) leaves dims unchanged") {
    LayerFixture fx;
    fx.writeSettings(R"({ "enabled": false })");
    mock::state().recommendedWidth = 1920;
    mock::state().recommendedHeight = 1080;
    mock::state().viewCount = 2;

    auto* layer = fx.boot();

    uint32_t count = 0;
    std::vector<XrViewConfigurationView> views(2, {XR_TYPE_VIEW_CONFIGURATION_VIEW});
    REQUIRE(layer->xrEnumerateViewConfigurationViews(
                reinterpret_cast<XrInstance>(static_cast<uintptr_t>(0xBEEF)),
                static_cast<XrSystemId>(1),
                XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO,
                2, &count, views.data()) == XR_SUCCESS);

    // Bypass path: layer must not rescale.
    CHECK(views[0].recommendedImageRectWidth == 1920u);
    CHECK(views[0].recommendedImageRectHeight == 1080u);
}

// ---------------------------------------------------------------------------
// xrLocateViews: FOV narrowed by the configured factors
// ---------------------------------------------------------------------------

TEST_CASE("integration: xrLocateViews narrows FOV per-edge") {
    LayerFixture fx;
    fx.writeSettings(R"({
        "enabled": true,
        "crop_left_percent": 10,
        "crop_right_percent": 20,
        "crop_top_percent": 15,
        "crop_bottom_percent": 25
    })");
    mock::state().viewCount = 2;
    mock::state().locateFovs = {defaultFov(), defaultFov()};

    auto* layer = fx.boot();

    uint32_t count = 0;
    std::vector<XrView> views(2, {XR_TYPE_VIEW});
    XrViewState viewState{XR_TYPE_VIEW_STATE};
    XrViewLocateInfo li{XR_TYPE_VIEW_LOCATE_INFO};
    li.viewConfigurationType = XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO;

    REQUIRE(layer->xrLocateViews(
                reinterpret_cast<XrSession>(static_cast<uintptr_t>(0xCAFE)),
                &li, &viewState, 2, &count, views.data()) == XR_SUCCESS);
    REQUIRE(count == 2);

    // Percents 10/20/15/25 map to tangent factors 0.80/0.60/0.70/0.50
    // via clampFactor = 1 - percent/50 (so percent 50 puts the bar at the
    // image center). Applied in tan-space so the factor corresponds
    // directly to a pixel fraction on the swapchain.
    CHECK(views[0].fov.angleLeft ==
          doctest::Approx(std::atan(std::tan(kDefaultLeftAngle) * 0.80f)));
    CHECK(views[0].fov.angleRight ==
          doctest::Approx(std::atan(std::tan(kDefaultRightAngle) * 0.60f)));
    CHECK(views[0].fov.angleUp ==
          doctest::Approx(std::atan(std::tan(kDefaultUpAngle) * 0.70f)));
    CHECK(views[0].fov.angleDown ==
          doctest::Approx(std::atan(std::tan(kDefaultDownAngle) * 0.50f)));
}

TEST_CASE("integration: xrLocateViews bypass path leaves FOV unchanged") {
    LayerFixture fx;
    fx.writeSettings(R"({ "enabled": false })");
    mock::state().viewCount = 2;
    mock::state().locateFovs = {defaultFov(), defaultFov()};

    auto* layer = fx.boot();

    uint32_t count = 0;
    std::vector<XrView> views(2, {XR_TYPE_VIEW});
    XrViewState viewState{XR_TYPE_VIEW_STATE};
    XrViewLocateInfo li{XR_TYPE_VIEW_LOCATE_INFO};

    REQUIRE(layer->xrLocateViews(
                reinterpret_cast<XrSession>(static_cast<uintptr_t>(0xCAFE)),
                &li, &viewState, 2, &count, views.data()) == XR_SUCCESS);

    CHECK(views[0].fov.angleLeft == doctest::Approx(kDefaultLeftAngle));
    CHECK(views[0].fov.angleRight == doctest::Approx(kDefaultRightAngle));
    CHECK(views[0].fov.angleUp == doctest::Approx(kDefaultUpAngle));
    CHECK(views[0].fov.angleDown == doctest::Approx(kDefaultDownAngle));
}

// ---------------------------------------------------------------------------
// Asymmetric FOV (WMR-style): each edge narrowed by its own factor
// ---------------------------------------------------------------------------

// WMR and Varjo report non-symmetric half-FOVs. Regressions in the signed-
// multiply logic only show up on asymmetric inputs, so we pin them.
TEST_CASE("integration: asymmetric WMR-style FOV narrows per-edge in xrLocateViews") {
    LayerFixture fx;
    fx.writeSettings(R"({
        "enabled": true,
        "crop_left_percent": 5,
        "crop_right_percent": 20,
        "crop_top_percent": 30,
        "crop_bottom_percent": 10
    })");
    const XrFovf wmrFov{-0.95f, 0.85f, 0.70f, -0.60f};
    mock::state().viewCount = 2;
    mock::state().locateFovs = {wmrFov, wmrFov};

    auto* layer = fx.boot();

    uint32_t count = 0;
    std::vector<XrView> views(2, {XR_TYPE_VIEW});
    XrViewState viewState{XR_TYPE_VIEW_STATE};
    XrViewLocateInfo li{XR_TYPE_VIEW_LOCATE_INFO};

    REQUIRE(layer->xrLocateViews(reinterpret_cast<XrSession>(static_cast<uintptr_t>(0xCAFE)),
                                 &li, &viewState, 2, &count, views.data()) == XR_SUCCESS);
    REQUIRE(count == 2);

    // Percents 5/20/30/10 map to tangent factors 0.90/0.60/0.40/0.80
    // (clampFactor = 1 - p/50). Applied in tan-space, each edge
    // independently on its own signed angle.
    CHECK(views[0].fov.angleLeft == doctest::Approx(std::atan(std::tan(-0.95f) * 0.90f)));
    CHECK(views[0].fov.angleRight == doctest::Approx(std::atan(std::tan(0.85f) * 0.60f)));
    CHECK(views[0].fov.angleUp == doctest::Approx(std::atan(std::tan(0.70f) * 0.40f)));
    CHECK(views[0].fov.angleDown == doctest::Approx(std::atan(std::tan(-0.60f) * 0.80f)));

    // Spec invariants that must hold after narrowing: left edge still negative,
    // right still positive, up still positive, down still negative. A bug in
    // the sign handling (e.g. taking abs() by mistake) would flip one of these.
    CHECK(views[0].fov.angleLeft < 0.0f);
    CHECK(views[0].fov.angleRight > 0.0f);
    CHECK(views[0].fov.angleUp > 0.0f);
    CHECK(views[0].fov.angleDown < 0.0f);
    // Ordering: left < right, down < up (narrower-than-original implied).
    CHECK(views[0].fov.angleLeft < views[0].fov.angleRight);
    CHECK(views[0].fov.angleDown < views[0].fov.angleUp);
}

// ---------------------------------------------------------------------------
// Live-edit: layer picks up settings.json changes after kLiveEditCheckInterval
// xrLocateViews calls (hard-coded to 90 in layer.cpp). We run that many
// frames, touch the file, and verify the next frame observes the new config.
// ---------------------------------------------------------------------------

TEST_CASE("integration: live_edit reloads settings.json at the poll interval") {
    LayerFixture fx;

    // Initial: 10% left crop -> factor 0.9.
    fx.writeSettings(R"({
        "enabled": true,
        "live_edit": true,
        "crop_left_percent": 10,
        "crop_right_percent": 10,
        "crop_top_percent": 10,
        "crop_bottom_percent": 10
    })");
    const XrFovf fov = defaultFov();
    mock::state().viewCount = 1;
    mock::state().locateFovs = {fov};

    auto* layer = fx.boot();

    auto locateFrame = [&]() -> XrView {
        uint32_t count = 0;
        std::vector<XrView> views(1, {XR_TYPE_VIEW});
        XrViewState viewState{XR_TYPE_VIEW_STATE};
        XrViewLocateInfo li{XR_TYPE_VIEW_LOCATE_INFO};
        li.viewConfigurationType = XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO;
        REQUIRE(layer->xrLocateViews(
                    reinterpret_cast<XrSession>(static_cast<uintptr_t>(0xCAFE)),
                    &li, &viewState, 1, &count, views.data()) == XR_SUCCESS);
        REQUIRE(count == 1);
        return views[0];
    };

    // First 89 frames: counter goes 1..89, no poll fires (90%90==0 is the
    // trigger). Config stays at factor 0.8 (percent 10 -> 1 - 10/50 = 0.8).
    const float expectedBefore = std::atan(std::tan(fov.angleLeft) * 0.8f);
    for (int i = 0; i < 89; ++i) {
        const auto v = locateFrame();
        CHECK(v.fov.angleLeft == doctest::Approx(expectedBefore));
    }

    // Rewrite the per-app file (not the settings.json template — the watcher
    // only monitors the per-app file) to 30% left crop -> factor 0.7. Sleep
    // a hair so the mtime tick is observable; Windows NTFS mtime has ~100ns
    // resolution but file-write APIs can coalesce same-second writes under
    // load.
    std::this_thread::sleep_for(std::chrono::milliseconds(50));
    fx.writePerAppSettings(R"({
        "enabled": true,
        "live_edit": true,
        "crop_left_percent": 30,
        "crop_right_percent": 10,
        "crop_top_percent": 10,
        "crop_bottom_percent": 10
    })");

    // Frame 90: counter hits 90, 90%90==0, poll fires, mtime changed -> reload.
    // The reload runs BEFORE the narrowFov call in xrLocateViews, so this
    // frame already sees the new factor (percent 30 -> 1 - 30/50 = 0.4).
    const float expectedAfter = std::atan(std::tan(fov.angleLeft) * 0.4f);
    const auto v = locateFrame();
    CHECK(v.fov.angleLeft == doctest::Approx(expectedAfter));
}

// ---------------------------------------------------------------------------
// Per-app config bootstrap: the first time an application runs, the layer
// creates its per-app settings file. If a global settings.json template
// exists, it is copied in; otherwise built-in defaults are written.
// ---------------------------------------------------------------------------

TEST_CASE("integration: per-app config is created from settings.json template on first boot") {
    LayerFixture fx;
    // Template exists, per-app file does not.
    fx.writeSettings(R"({ "enabled": true, "crop_left_percent": 42 })");
    REQUIRE(!std::filesystem::exists(fx.configDir / "test_settings.json"));

    fx.boot();

    // After boot, the per-app file exists and carries the template's values.
    REQUIRE(std::filesystem::exists(fx.configDir / "test_settings.json"));
    std::ifstream in(fx.configDir / "test_settings.json");
    std::string content((std::istreambuf_iterator<char>(in)),
                        std::istreambuf_iterator<char>());
    CHECK(content.find("\"crop_left_percent\": 42") != std::string::npos);
}

TEST_CASE("integration: settings.json template is auto-created on first boot if absent") {
    LayerFixture fx;
    REQUIRE(!std::filesystem::exists(fx.configDir / "settings.json"));

    fx.boot();

    // The layer creates a template file with the built-in defaults so the
    // user has a single place to tune the defaults applied to future games.
    REQUIRE(std::filesystem::exists(fx.configDir / "settings.json"));
    std::ifstream in(fx.configDir / "settings.json");
    std::string content((std::istreambuf_iterator<char>(in)),
                        std::istreambuf_iterator<char>());
    CHECK(content.find("\"crop_left_percent\"") != std::string::npos);
    CHECK(content.find("\"enabled\"") != std::string::npos);
    // Template comment distinguishes it from a per-app file.
    CHECK(content.find("Default template") != std::string::npos);
}

TEST_CASE("integration: existing settings.json template is not overwritten by boot") {
    LayerFixture fx;
    const std::string original = R"({ "enabled": true, "crop_left_percent": 99 })";
    fx.writeSettings(original);

    fx.boot();

    std::ifstream in(fx.configDir / "settings.json");
    std::string content((std::istreambuf_iterator<char>(in)),
                        std::istreambuf_iterator<char>());
    // Still the user's content, byte for byte.
    CHECK(content == original);
}

TEST_CASE("integration: per-app config is bootstrapped from the auto-created template") {
    LayerFixture fx;
    // Clean slate: no template, no per-app file.
    REQUIRE(!std::filesystem::exists(fx.configDir / "settings.json"));
    REQUIRE(!std::filesystem::exists(fx.configDir / "test_settings.json"));

    fx.boot();

    // Both files now exist, and the per-app file is a copy of the template
    // (so it carries the template's _comment — minor cosmetic detail the
    // user can ignore or edit out).
    REQUIRE(std::filesystem::exists(fx.configDir / "settings.json"));
    REQUIRE(std::filesystem::exists(fx.configDir / "test_settings.json"));

    std::ifstream tIn(fx.configDir / "settings.json");
    std::string tContent((std::istreambuf_iterator<char>(tIn)),
                         std::istreambuf_iterator<char>());
    std::ifstream pIn(fx.configDir / "test_settings.json");
    std::string pContent((std::istreambuf_iterator<char>(pIn)),
                         std::istreambuf_iterator<char>());
    CHECK(tContent == pContent);
}

TEST_CASE("integration: existing per-app config is not overwritten by subsequent boot") {
    LayerFixture fx;
    // Pre-populate a per-app file directly.
    fx.writePerAppSettings(R"({ "enabled": true, "crop_left_percent": 7 })");
    // Also drop a different template; it should be IGNORED because per-app
    // already exists.
    fx.writeSettings(R"({ "enabled": true, "crop_left_percent": 99 })");

    fx.boot();

    // Per-app file still carries the 7 value, not the 99 from the template.
    std::ifstream in(fx.configDir / "test_settings.json");
    std::string content((std::istreambuf_iterator<char>(in)),
                        std::istreambuf_iterator<char>());
    CHECK(content.find("\"crop_left_percent\": 7") != std::string::npos);
    CHECK(content.find("\"crop_left_percent\": 99") == std::string::npos);
}

// ---------------------------------------------------------------------------
// Const-input hygiene: the layer must never mutate any struct the caller
// passed as a const input. A const_cast / aliasing bug could regress this.
// We compare byte-for-byte before vs after. POD-only structs make memcmp
// sound here (no padding-holes concerns since the compiler lays them out
// deterministically within a single TU).
// ---------------------------------------------------------------------------

TEST_CASE("integration: layer never mutates caller's const inputs") {
    LayerFixture fx;
    fx.writeSettings(R"({
        "enabled": true,
        "crop_left_percent": 10,
        "crop_right_percent": 15,
        "crop_top_percent": 20,
        "crop_bottom_percent": 25
    })");
    mock::state().viewCount = 2;
    mock::state().locateFovs = {defaultFov(), defaultFov()};

    auto* layer = fx.boot();

    // --- xrLocateViews: locateInfo must be untouched. ---
    XrViewLocateInfo locateInfo{XR_TYPE_VIEW_LOCATE_INFO};
    locateInfo.viewConfigurationType = XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO;
    locateInfo.displayTime = 42;
    locateInfo.space = reinterpret_cast<XrSpace>(static_cast<uintptr_t>(0xBADF00D));
    const XrViewLocateInfo locateInfoCopy = locateInfo;

    uint32_t count = 0;
    std::vector<XrView> outViews(2, {XR_TYPE_VIEW});
    XrViewState viewState{XR_TYPE_VIEW_STATE};
    REQUIRE(layer->xrLocateViews(reinterpret_cast<XrSession>(static_cast<uintptr_t>(0xCAFE)),
                                 &locateInfo, &viewState, 2, &count, outViews.data()) ==
            XR_SUCCESS);
    CHECK(std::memcmp(&locateInfo, &locateInfoCopy, sizeof(locateInfo)) == 0);
}
