// MIT License
//
// Copyright (c) 2026 mledour
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and /or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions :
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Integration tests: drive the real OpenXrLayer class (from layer.cpp) against
// the mock runtime defined in mock_runtime.{h,cpp}. These tests link the
// layer's dispatch machinery so they cover the actual virtual-method plumbing
// generated by dispatch_generator.py — not a hand-rolled copy.
//
// What we do NOT cover here (intentionally): the loader handshake
// (xrNegotiateLoaderApiLayerInterface, xrCreateApiLayerInstance). Those
// need a live loader and are verified by the end-to-end job on a self-hosted
// runner. Everything else that happens after the layer has been handed an
// XrInstance — config parsing, view scaling, FOV narrowing, swapchain crop —
// is in scope.

#include "pch.h"

#include "mock_runtime.h"

#include <layer.h>
#include <utils/crop_math.h>

#include <doctest/doctest.h>

#include <cstdio>
#include <filesystem>
#include <fstream>
#include <random>

using openxr_api_layer::GetInstance;
using openxr_api_layer::OpenXrApi;

namespace {

// Every TEST_CASE creates a fresh layer singleton + mock state, so tests are
// order-independent. We also isolate %LOCALAPPDATA% to a unique temp dir per
// test so settings.json handling is deterministic on CI where the real
// %LOCALAPPDATA%\XR_APILAYER_MLEDOUR_fov_crop\ might exist with user data.
struct LayerFixture {
    std::filesystem::path configDir;

    LayerFixture() {
        mock::reset();
        openxr_api_layer::ResetInstance();

        // Unique temp dir avoids clashes if tests run in parallel one day.
        std::random_device rd;
        auto suffix = std::to_string(rd());
        configDir = std::filesystem::temp_directory_path() /
                    ("openxr-layer-test-" + suffix);
        std::filesystem::create_directories(configDir);
        openxr_api_layer::localAppData = configDir;
        openxr_api_layer::dllHome = configDir;
    }

    ~LayerFixture() {
        openxr_api_layer::ResetInstance();
        std::error_code ec;
        std::filesystem::remove_all(configDir, ec);
    }

    // Writes settings.json into the fixture's localAppData. Pass empty string
    // to skip (layer will use defaults).
    void writeSettings(const std::string& json) {
        if (json.empty()) return;
        std::ofstream f(configDir / "settings.json");
        f << json;
    }

    // Brings the layer up the same way xrCreateApiLayerInstance would:
    // wire GIPA -> call xrCreateInstance -> resolve every function we plan to
    // exercise (so the m_xrFoo pointers in OpenXrApi are populated via the
    // generated xrGetInstanceProcAddrInternal path).
    OpenXrApi* boot() {
        OpenXrApi* layer = GetInstance();
        REQUIRE(layer != nullptr);

        // XrInstance here is a fake handle — the layer never dereferences it,
        // just threads it back to the mock via m_xrGetInstanceProcAddr.
        XrInstance fakeInstance = reinterpret_cast<XrInstance>(static_cast<uintptr_t>(0xBEEF));
        layer->SetGetInstanceProcAddr(&mock::xrGetInstanceProcAddr, fakeInstance);

        XrInstanceCreateInfo ici{XR_TYPE_INSTANCE_CREATE_INFO};
        std::strncpy(ici.applicationInfo.applicationName, "test", XR_MAX_APPLICATION_NAME_SIZE - 1);
        ici.applicationInfo.apiVersion = XR_CURRENT_API_VERSION;

        REQUIRE(layer->xrCreateInstance(&ici) == XR_SUCCESS);

        // Resolve the entry points the tests will call. This is what the
        // loader does after xrCreateApiLayerInstance: each of these calls
        // populates m_xrFoo inside OpenXrApi via the generated
        // xrGetInstanceProcAddrInternal. We never use the returned function
        // pointers — we go through the virtual methods instead.
        //
        // We explicitly target OpenXrApi::xrGetInstanceProcAddr (the base,
        // non-bypassed implementation). The OpenXrLayer override short-circuits
        // to raw runtime pointers when m_bypassApiLayer is true, which skips
        // the m_xrFoo population and would leave the test calling null in
        // bypass-enabled test cases. Going through the base always populates
        // the dispatch table so subsequent virtual calls are safe to make;
        // the override's enabled-check still governs whether the layer
        // mutates results.
        auto resolve = [&](const char* name) {
            PFN_xrVoidFunction fn = nullptr;
            REQUIRE(layer->OpenXrApi::xrGetInstanceProcAddr(fakeInstance, name, &fn) == XR_SUCCESS);
        };
        resolve("xrGetSystem");
        resolve("xrCreateSession");
        resolve("xrDestroySession");
        resolve("xrEnumerateViewConfigurationViews");
        resolve("xrLocateViews");
        resolve("xrCreateSwapchain");
        resolve("xrDestroySwapchain");
        resolve("xrEndFrame");

        return layer;
    }
};

constexpr float kDefaultLeftAngle = -0.90f;
constexpr float kDefaultRightAngle = 0.90f;
constexpr float kDefaultUpAngle = 0.70f;
constexpr float kDefaultDownAngle = -0.70f;

XrFovf defaultFov() {
    return XrFovf{kDefaultLeftAngle, kDefaultRightAngle, kDefaultUpAngle, kDefaultDownAngle};
}

} // namespace

// ---------------------------------------------------------------------------
// xrEnumerateViewConfigurationViews: recommended dims shrink per config
// ---------------------------------------------------------------------------

TEST_CASE("integration: xrEnumerateViewConfigurationViews scales recommended dims") {
    LayerFixture fx;
    // 10/10/15/20% crop -> factors 0.9/0.9/0.85/0.80.
    // scaleSwapchainExtents uses min(left,right)=0.9 for width, min(top,bot)=0.80 for height.
    // 2000*0.9 = 1800 (8-aligned: 1800), 2200*0.8 = 1760 (8-aligned: 1760).
    fx.writeSettings(R"({
        "enabled": true,
        "crop_left_percent": 10,
        "crop_right_percent": 10,
        "crop_top_percent": 15,
        "crop_bottom_percent": 20
    })");
    mock::state().recommendedWidth = 2000;
    mock::state().recommendedHeight = 2200;
    mock::state().viewCount = 2;

    auto* layer = fx.boot();

    uint32_t count = 0;
    REQUIRE(layer->xrEnumerateViewConfigurationViews(
                reinterpret_cast<XrInstance>(static_cast<uintptr_t>(0xBEEF)),
                static_cast<XrSystemId>(1),
                XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO,
                0, &count, nullptr) == XR_SUCCESS);
    REQUIRE(count == 2);

    std::vector<XrViewConfigurationView> views(count, {XR_TYPE_VIEW_CONFIGURATION_VIEW});
    REQUIRE(layer->xrEnumerateViewConfigurationViews(
                reinterpret_cast<XrInstance>(static_cast<uintptr_t>(0xBEEF)),
                static_cast<XrSystemId>(1),
                XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO,
                count, &count, views.data()) == XR_SUCCESS);

    // Expected: 2000 * 0.9 = 1800, aligned-down to 8 -> 1800. 2200 * 0.8 = 1760.
    CHECK(views[0].recommendedImageRectWidth == 1800u);
    CHECK(views[0].recommendedImageRectHeight == 1760u);
    CHECK(views[1].recommendedImageRectWidth == 1800u);
    CHECK(views[1].recommendedImageRectHeight == 1760u);
}

TEST_CASE("integration: bypass (enabled=false) leaves dims unchanged") {
    LayerFixture fx;
    fx.writeSettings(R"({ "enabled": false })");
    mock::state().recommendedWidth = 1920;
    mock::state().recommendedHeight = 1080;
    mock::state().viewCount = 2;

    auto* layer = fx.boot();

    uint32_t count = 0;
    std::vector<XrViewConfigurationView> views(2, {XR_TYPE_VIEW_CONFIGURATION_VIEW});
    REQUIRE(layer->xrEnumerateViewConfigurationViews(
                reinterpret_cast<XrInstance>(static_cast<uintptr_t>(0xBEEF)),
                static_cast<XrSystemId>(1),
                XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO,
                2, &count, views.data()) == XR_SUCCESS);

    // Bypass path: layer must not rescale.
    CHECK(views[0].recommendedImageRectWidth == 1920u);
    CHECK(views[0].recommendedImageRectHeight == 1080u);
}

// ---------------------------------------------------------------------------
// xrLocateViews: FOV narrowed by the configured factors
// ---------------------------------------------------------------------------

TEST_CASE("integration: xrLocateViews narrows FOV per-edge") {
    LayerFixture fx;
    fx.writeSettings(R"({
        "enabled": true,
        "crop_left_percent": 10,
        "crop_right_percent": 20,
        "crop_top_percent": 15,
        "crop_bottom_percent": 25
    })");
    mock::state().viewCount = 2;
    mock::state().locateFovs = {defaultFov(), defaultFov()};

    auto* layer = fx.boot();

    uint32_t count = 0;
    std::vector<XrView> views(2, {XR_TYPE_VIEW});
    XrViewState viewState{XR_TYPE_VIEW_STATE};
    XrViewLocateInfo li{XR_TYPE_VIEW_LOCATE_INFO};
    li.viewConfigurationType = XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO;

    REQUIRE(layer->xrLocateViews(
                reinterpret_cast<XrSession>(static_cast<uintptr_t>(0xCAFE)),
                &li, &viewState, 2, &count, views.data()) == XR_SUCCESS);
    REQUIRE(count == 2);

    // Factors: 0.90, 0.80, 0.85, 0.75.
    CHECK(views[0].fov.angleLeft == doctest::Approx(kDefaultLeftAngle * 0.90f));
    CHECK(views[0].fov.angleRight == doctest::Approx(kDefaultRightAngle * 0.80f));
    CHECK(views[0].fov.angleUp == doctest::Approx(kDefaultUpAngle * 0.85f));
    CHECK(views[0].fov.angleDown == doctest::Approx(kDefaultDownAngle * 0.75f));
}

TEST_CASE("integration: xrLocateViews bypass path leaves FOV unchanged") {
    LayerFixture fx;
    fx.writeSettings(R"({ "enabled": false })");
    mock::state().viewCount = 2;
    mock::state().locateFovs = {defaultFov(), defaultFov()};

    auto* layer = fx.boot();

    uint32_t count = 0;
    std::vector<XrView> views(2, {XR_TYPE_VIEW});
    XrViewState viewState{XR_TYPE_VIEW_STATE};
    XrViewLocateInfo li{XR_TYPE_VIEW_LOCATE_INFO};

    REQUIRE(layer->xrLocateViews(
                reinterpret_cast<XrSession>(static_cast<uintptr_t>(0xCAFE)),
                &li, &viewState, 2, &count, views.data()) == XR_SUCCESS);

    CHECK(views[0].fov.angleLeft == doctest::Approx(kDefaultLeftAngle));
    CHECK(views[0].fov.angleRight == doctest::Approx(kDefaultRightAngle));
    CHECK(views[0].fov.angleUp == doctest::Approx(kDefaultUpAngle));
    CHECK(views[0].fov.angleDown == doctest::Approx(kDefaultDownAngle));
}

// ---------------------------------------------------------------------------
// xrEndFrame: fov and imageRect on submitted projection views
// ---------------------------------------------------------------------------

TEST_CASE("integration: xrEndFrame rewrites fov and imageRect on projection layer") {
    LayerFixture fx;
    fx.writeSettings(R"({
        "enabled": true,
        "crop_left_percent": 10,
        "crop_right_percent": 10,
        "crop_top_percent": 15,
        "crop_bottom_percent": 20
    })");
    mock::state().viewCount = 2;

    auto* layer = fx.boot();

    // Register a swapchain through the layer so its internal map knows the
    // dims. xrEndFrame uses those to project the FOV crop onto pixel space.
    constexpr uint32_t kSwapWidth = 1920;
    constexpr uint32_t kSwapHeight = 2160;
    XrSwapchainCreateInfo sci{XR_TYPE_SWAPCHAIN_CREATE_INFO};
    sci.width = kSwapWidth;
    sci.height = kSwapHeight;
    sci.faceCount = 1;
    sci.arraySize = 1;
    sci.mipCount = 1;
    sci.sampleCount = 1;
    sci.format = 0x1234; // layer treats this opaquely
    sci.usageFlags = XR_SWAPCHAIN_USAGE_COLOR_ATTACHMENT_BIT;

    XrSwapchain sc = XR_NULL_HANDLE;
    REQUIRE(layer->xrCreateSwapchain(
                reinterpret_cast<XrSession>(static_cast<uintptr_t>(0xCAFE)),
                &sci, &sc) == XR_SUCCESS);
    REQUIRE(sc != XR_NULL_HANDLE);

    // Build a projection layer with the app's rendered FOV.
    XrCompositionLayerProjectionView appViews[2]{};
    for (int i = 0; i < 2; ++i) {
        appViews[i].type = XR_TYPE_COMPOSITION_LAYER_PROJECTION_VIEW;
        appViews[i].fov = defaultFov();
        appViews[i].subImage.swapchain = sc;
        appViews[i].subImage.imageRect = {{0, 0}, {static_cast<int32_t>(kSwapWidth), static_cast<int32_t>(kSwapHeight)}};
        appViews[i].subImage.imageArrayIndex = i;
    }

    XrCompositionLayerProjection projLayer{XR_TYPE_COMPOSITION_LAYER_PROJECTION};
    projLayer.viewCount = 2;
    projLayer.views = appViews;

    const XrCompositionLayerBaseHeader* layers[1] = {
        reinterpret_cast<const XrCompositionLayerBaseHeader*>(&projLayer),
    };
    XrFrameEndInfo fei{XR_TYPE_FRAME_END_INFO};
    fei.layerCount = 1;
    fei.layers = layers;
    fei.displayTime = 1;
    fei.environmentBlendMode = XR_ENVIRONMENT_BLEND_MODE_OPAQUE;

    REQUIRE(layer->xrEndFrame(reinterpret_cast<XrSession>(static_cast<uintptr_t>(0xCAFE)),
                              &fei) == XR_SUCCESS);

    // The layer must not mutate the caller's struct — that would be a
    // spec violation (frameEndInfo is const).
    CHECK(appViews[0].fov.angleLeft == doctest::Approx(kDefaultLeftAngle));
    CHECK(appViews[0].subImage.imageRect.extent.width == static_cast<int32_t>(kSwapWidth));

    // The mock recorded what the layer submitted downstream.
    REQUIRE(mock::state().endFrameCallCount == 1);
    REQUIRE(mock::state().lastEndFrameProjLayers.size() == 1);
    const auto& submitted = mock::state().lastEndFrameProjLayers[0].views;
    REQUIRE(submitted.size() == 2);

    // FOV was narrowed.
    CHECK(submitted[0].fov.angleLeft == doctest::Approx(kDefaultLeftAngle * 0.90f));
    CHECK(submitted[0].fov.angleRight == doctest::Approx(kDefaultRightAngle * 0.90f));
    CHECK(submitted[0].fov.angleUp == doctest::Approx(kDefaultUpAngle * 0.85f));
    CHECK(submitted[0].fov.angleDown == doctest::Approx(kDefaultDownAngle * 0.80f));

    // imageRect shrank. Sanity bounds — the rect stays inside the swapchain
    // and has positive area. Exact pixel values are covered by the crop_math
    // unit tests; here we just confirm the layer plumbs them through.
    const auto& rect = submitted[0].subImage.imageRect;
    CHECK(rect.offset.x >= 0);
    CHECK(rect.offset.y >= 0);
    CHECK(rect.extent.width > 0);
    CHECK(rect.extent.height > 0);
    CHECK(rect.offset.x + rect.extent.width <= static_cast<int32_t>(kSwapWidth));
    CHECK(rect.offset.y + rect.extent.height <= static_cast<int32_t>(kSwapHeight));
    // Cropped area must be strictly smaller than the full swapchain.
    CHECK(static_cast<uint32_t>(rect.extent.width) < kSwapWidth);
    CHECK(static_cast<uint32_t>(rect.extent.height) < kSwapHeight);
}

TEST_CASE("integration: xrEndFrame passes through non-projection layers untouched") {
    LayerFixture fx;
    fx.writeSettings(R"({ "enabled": true })");
    mock::state().viewCount = 2;

    auto* layer = fx.boot();

    // A quad layer — not a projection layer, so the crop logic must skip it.
    XrCompositionLayerQuad quad{XR_TYPE_COMPOSITION_LAYER_QUAD};
    const XrCompositionLayerBaseHeader* layers[1] = {
        reinterpret_cast<const XrCompositionLayerBaseHeader*>(&quad),
    };
    XrFrameEndInfo fei{XR_TYPE_FRAME_END_INFO};
    fei.layerCount = 1;
    fei.layers = layers;
    fei.displayTime = 1;
    fei.environmentBlendMode = XR_ENVIRONMENT_BLEND_MODE_OPAQUE;

    REQUIRE(layer->xrEndFrame(reinterpret_cast<XrSession>(static_cast<uintptr_t>(0xCAFE)),
                              &fei) == XR_SUCCESS);

    // Mock recorded no projection layers — the quad was forwarded, but our
    // recorder only snapshots projection layers.
    CHECK(mock::state().endFrameCallCount == 1);
    CHECK(mock::state().lastEndFrameProjLayers.empty());
}
